pets-oss/pets-back

- CODE_OF_CONDUCT.md
- README.md
Please get acquainted to our Contributor Covenant Code of Conduct
> #14 Add code of conduct

- LICENSE
We had a vote to choose a license. It turned out to be a tie. Later as discussed in a meeting, we are choosing MIT license
> #9 Add license

- database/data.sql
- database/schema.sql
Added tables with sample data according to ER diagram. Few notes:
a) I could not go with table name "user" because this is a reserved word in postgresql. Now it's a little weird that all tables are in singular except one is in plural. Should we rename users or go with plural names for tables?
b) Few-word column naming is different. Sometimes it's snake_case (full_name, registration_no etc.) and sometimes it's camelCase (dateTime, imageUrl etc.). I believe we should unify the style.
c) From the diagram I did not understand the data type of eventType. Should it be an enum? For now I just made it a VARCHAR to be more flexible since we do not know all the possible event types and they might change in the future.
d) We might need a time-zone aware timestamp but I am not sure about it at the …
> #12 Create DB tables according to class diagram

- database/data.sql
- database/schema.sql
From https://github.com/pets-oss/pets-back/issues/21
- make foreign keys NOT NULL
- make primary keys NOT NULL
- convert breed to an ENUM
> Improve database #21

- package-lock.json
- package.json
- src/index.ts
Add CORS policy without it GQL front client requests will be blocked.
> CORS policy

- database/4-change_structure.sql
- src/schemas/animal.ts
- src/sql-queries/animal.ts
- Removed `organization` column from `event` tables
- Created `app_user_role` table - one user may have role in more than 1 organisation
- Removed street address slitting from `organization` table - IMO we don't need 3 columns for street address (street, house and flat)
- created `animal_registration` table to store registration data and added `status` column to track if that registration is active
- created `animal_microchip` table to store microchip data and added `status` column to track if that chip is implanted
- created `animal_details` table to split animal general info from `animal` table
> Changed database structure

- src/schemas/animal.ts
- src/schemas/animalDetails.ts
- src/schemas/animalMicrochip.ts
- src/schemas/animalRegistration.ts
- src/schemas/index.ts
- src/sql-queries/animal.ts
- test/animal.interface.ts
- test/animal.interface.validator.ts
Closes #32
Closes #33 
<details>
<summary>Create animal example</summary>
```graphql
mutation {
createAnimal(input: {
name: "Reksas",
organization: 2,
status: "sick",
image_url: "https://cdn.pixabay.com/photo/2017/10/07/11/52/dog-2826297_1280.jpg",
comments: "Nice dog"}) {
id
name
organization
status
image_url
comments
mod_time
}
}
```
</details>
<details>
<summary>Update animal example</summary>
```graphql
mutation {
updateAnimal(input: {
id: 1,
name: "Reksas",
organization: 2,
status: "sick",
image_url: "https://cdn.pixabay.com/photo/2017/10/07/11/52/dog-2826297_1280.jpg",
comments: "Nice dog"}) {
id
name
organization
status
image_url
comments
mod_time
}
}
```
</details>
> 32 33 - create, update animal entity

- database/1-schema.sql
- package-lock.json
- package.json
- src/decs.d.ts
- src/schema/index.ts
- src/schema/resolvers/organization.ts
- src/schema/typeDefs/organization.graphql
- src/sql-queries/organization.ts
Added validation solution as well.
> 68 organization query and mutation

- database/1-schema.sql
- package-lock.json
- src/schema/index.ts
- src/schema/resolvers/animal.ts
- src/schema/resolvers/animalMicrochip.ts
- src/schema/typeDefs/animalMicrochip.graphql
- src/sql-queries/animalMicrochip.ts
- test/animalMIcrochip.graphql.test.ts
- test/testFields.ts
> 77 - add mutation for animal microchip

- database/1-schema.sql
- src/schema/resolvers/animal.ts
- src/schema/typeDefs/animal.graphql
- src/sql-queries/animal.ts
- test/animal.graphql.test.ts
Closes #34 
Example:
<details>
<summary>Animal deletion</summary>
```graphql
mutation {
deleteAnimal(input: {id: 2}) {
id
name
}
}
```
</details>
> 34 - add animal delete mutation

- database/3-fake-data.sql
> #136 Add dummy events for animals 

- database/1-schema.sql
- database/3-fake-data.sql
- src/index.ts
Added table to store users favorite animals
https://github.com/pets-oss/pets-back/issues/141
> 141 | Added animal favorite table

- database/1-schema.sql
Workshop task (Database Issues A, No. 6 from slides).
**Resolves issue #154**
> [#154]-[Add mod_time column for former_animal_owner table]

- src/schema/index.ts
- src/schema/resolvers/chipCompany.ts
- src/schema/typeDefs/chipCompany.graphql
- src/sql-queries/chipCompany.ts
- test/chipCompany.graphql.test.ts
Created a GraphQL query that returns all chip companies from the database and wrote an automatic test to check if the query works correctly. Solves issue #118.
> #118 Add query to get all available chip companies

- reports.sql
- src/schema/index.ts
- src/schema/resolvers/date.ts
- src/schema/scalars/Date.ts
- src/schema/typeDefs/date.graphql
- test/date.test.ts
Date scalar is string matching YYYY-MM-DD format, throws Error in case of format violation or invalid date (e.g. 2021-02-30).
>  #132 Create Date scalar

- database/3-fake-data.sql
> Align fake data animal names and genders

- database/1-schema.sql
- database/3-fake-data.sql
Additionally trimming whitespace
> Create table for LocationChange event details #261

- src/schema/resolvers/animal.ts
- src/schema/typeDefs/animal.graphql
- src/sql-queries/animal.ts
- src/sql-queries/favoriteAnimal.ts
- test/animal.graphql.test.ts
- test/interfaces/animal.interface.ts
- test/validators/animal.interface.validator.ts
Supplemented `Animal` object with `isFavorite` flag which determines if an animal is marked as favorite by the current user. Resolves #268.
> #268 Return isFavorite flag with Animal object

- src/schema/resolvers/favoriteAnimal.ts
One more fix. I will add tests later since this is an urgent request to fix it.
> Favorite animals query fix

- src/schema/resolvers/animal.ts
- src/schema/typeDefs/animal.graphql
> #287 Make AnimalRegistrationInput optional when creating animal
